# Generated by Django 5.2.5 on 2025-09-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='board_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='brcb',
            field=models.CharField(blank=True, help_text='Buffered Report Control Block', max_length=64),
        ),
        migrations.AddField(
            model_name='device',
            name='memory_iec',
            field=models.CharField(blank=True, default='true', max_length=5),
        ),
        migrations.AddField(
            model_name='device',
            name='scl_file',
            field=models.CharField(blank=True, help_text='SCL File Path', max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='urcb',
            field=models.CharField(blank=True, help_text='Unbuffered Report Control Block', max_length=64),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('PV', 'PV Panel'), ('WindTurbine', 'Wind Turbine'), ('FuelTurbine', 'Fuel Turbine'), ('FuelCell', 'Fuel Cell'), ('BESS', 'BESS'), ('IED', 'IED')], max_length=20),
        ),
    ]
